
package edu.kalum.workerenrollment.core.client.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEnrollmentService", targetNamespace = "http://beans.core.enrollment.kalum.edu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEnrollmentService {


    /**
     * 
     * @param arg0
     * @return
     *     returns edu.kalum.workerenrollment.core.client.services.EnrollmentResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enrollmentProcess", targetNamespace = "http://beans.core.enrollment.kalum.edu/", className = "edu.kalum.workerenrollment.core.client.services.EnrollmentProcess")
    @ResponseWrapper(localName = "enrollmentProcessResponse", targetNamespace = "http://beans.core.enrollment.kalum.edu/", className = "edu.kalum.workerenrollment.core.client.services.EnrollmentProcessResponse")
    @Action(input = "http://beans.core.enrollment.kalum.edu/IEnrollmentService/enrollmentProcessRequest", output = "http://beans.core.enrollment.kalum.edu/IEnrollmentService/enrollmentProcessResponse")
    public EnrollmentResponse enrollmentProcess(
        @WebParam(name = "arg0", targetNamespace = "")
        EnrollmentRequest arg0);

}
